package nl.digischool.wrts.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordListDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final WordListDao wordListDao;
    private final WordDao wordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordListDaoConfig = daoConfigMap.get(WordListDao.class).clone();
        wordListDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        wordListDao = new WordListDao(wordListDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(WordList.class, wordListDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        wordListDaoConfig.getIdentityScope().clear();
        wordDaoConfig.getIdentityScope().clear();
    }

    public WordListDao getWordListDao() {
        return wordListDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
